### ISSUE TITLE
This option belongs to all folders, not only desktop

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#116]
![изображение](https://user-images.githubusercontent.com/1271736/224515692-b84103ae-14f0-4f21-9a56-07ba1dd4ec50.png)

**Comment by Abdelrhman-AK** [comment]
- When I tested it on desktop it worked:
![Screenshot 2023-03-12 161422](https://user-images.githubusercontent.com/59510211/224550425-aae62c51-605d-44b2-b1b3-4990ee3efbdb.png)

- Unlike inside the explorer, it didn't work:
![Screenshot 2023-03-12 161449](https://user-images.githubusercontent.com/59510211/224550440-b21a3404-77bb-4d04-9482-7fb9981ee0af.png)

- And is this maybe due to your universal classic theme

**Comment by Anixx** [comment]
Well, more likely it is due to SysListView32. It is used on desktop in all Windows versions.

**Comment by Anixx** [comment]
Windows itself does not mention that it affects only desktop in Performance Settings.

**Comment by Abdelrhman-AK** [comment]
> Windows itself does not mention that it affects only desktop in Performance Settings.

I'll rename it to make it match the system's one

**Comment by Anixx** [comment]
Indeed, I think it affects all apps that use SysListView32 control, and this control is quite common.
