### ISSUE TITLE
In Win32 color settings the color of the menu bar seems wrong

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#15]
Here is the issue, in notepad the color is blue, in the preview it is grey. The same grey color remains under all color schemes. The menu item highlight color is also wrong:

![изображение](https://user-images.githubusercontent.com/1271736/181834477-de63287a-ab0e-47dc-997c-6d0d12306355.png)

The pictograms on the window buttons (such as the [X]) also seem to be of the wrong size.

**Comment by Anixx** [comment]
I also suggest to change the description to "These are applicable only for some Windows Elements (...) and unthemed apps (such as VB6).

Notice that otvdm has option to run apps in themed mode, it is just not default (for compatibility reasons).

**Comment by Abdelrhman-AK** [comment]
I'll fix these issues in the next version

**Comment by OrthodoxWindows** [comment]
@Anixx I don't consider this a bug, because what shows in the WinPaletter preview is the configuration with userpreferencemask bit 17 (visible in UPMcalc) enabled. In your configuration, bit 17 is disabled, which disables the menubar and menuhilight parameters, and these parameters become managed by the menu and hilight parameters (which is not the default configuration). It was found in this thread: https://winclassic.boards.net/thread/1246/menubar-menuhilight-settings-useful
Although most color schemes are configured for bit 17 disabled, it is quite possible to create color schemes with, for example, a menu bar color different from the menu colors, or even with a menu selection color different from the text selection color. Especially since most users don't use WinPaletter with the classic theme, let alone with userpreferencemask bit 17 disabled. So this may cause confusion for a user who just wants to, for example, configure the colors of win16 programs in OTVDM (because in a default configuration, the current preview of win32 controls works correctly).

@Abdelrhman-AK So what I suggest is to add a system for detecting the activation of bit 17 of userpreferencemask, and displaying it accordingly. If this is not possible, a manual command on the dialog box or the user indicates whether bit 17 is activated or not.

**Comment by OrthodoxWindows** [comment]
Here is documentation on the userpreferencemask key (not really up to date, because the key has evolved in Windows 10): https://msfn.org/board/topic/73209-hkcucontrol-paneldesktopuserpreferencesmask/
https://msfn.org/board/topic/144738-upmcalc/
