### ISSUE TITLE
Windows version false positive after installing Windows 7 icon pack

### ISSUE THREAD

**Issue by Cynosphere** [Abdelrhman-AK/WinPaletter#164]
## **Describe the bug**
WinPaletter thinks the OS is Windows 7 after applying a Windows 7 icon pack that modifies winver on Windows 10

## **WinPaletter Log**
N/A

## **Screenshots/Screen records**
N/A

## **Additional context**
https://www.deviantart.com/luximoz/art/7TSP-UpdatedSevenifier-Winver-fix-970479301

**Comment by Abdelrhman-AK** [comment]
- That is because of the patched `basebrd.dll.res` file inside the theme pack.
- WinPaletter gets current OS name from property `Computer.Info.OSFullName` that mainly depends on `basebrd.dll.res`.
- Here you are the difference between original (untouched) `basebrd.dll.res` and the patched `basebrd.dll.res`.
![0](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/c107ee05-8819-4e47-8e17-e964fc7b5824)
- When I modified it to Windows XP myself, WinPaletter detected that the current OS is Windows XP.
![1](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/bce6fb04-f90d-4749-af69-f14a5130e5b8)
- Try to restore your system to default by 7tsp, then modify the ZIP theme pack by deleting `basebrd.dll.res` inside `resources` directory and finally patch your Windows by the new ZIP.

**Comment by Cynosphere** [comment]
Thanks

**Comment by Abdelrhman-AK** [comment]
You're welcome!
