### ISSUE TITLE
No option to change the message text color? Or I was unable to find?

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#18]
I mean, this:

![изображение](https://user-images.githubusercontent.com/1271736/181916353-3e24f314-3992-4a14-94b2-aa0d5eb59fd2.png)

**Comment by Abdelrhman-AK** [comment]
It is a bug in the previewer too,
You can edit it from Window Objects Section > Window Text

**Comment by Anixx** [comment]
The color of the text in menubar also seems to be invariably black.

**Comment by Abdelrhman-AK** [comment]
Is this in the previewer only or both previewer and Windows?

I'll investigate more about the previewer as it has bugs and test colors..
I'll fix it in the next release.

**Comment by Anixx** [comment]
Only in the previewer.

**Comment by Abdelrhman-AK** [comment]
Ok. That's fine.. I'll fix the previewer
Thanks for your contribution!

**Comment by OrthodoxWindows** [comment]
I found two other problems: the color of the ClientEdge in the previewer (the interior borders of the windows) is invariable, as well as the color of the menus border.

The problem only arises with the previewer ; when applying colors it works fine.

**Comment by Abdelrhman-AK** [comment]
Can you post here a screenshot?
It will be easier to fix for me.

**Comment by OrthodoxWindows** [comment]
Here are the screenshots:
The ClientEdge is the interior edge of the windows :
![notepad_kaO9myI77j](https://user-images.githubusercontent.com/100134023/183254818-0c13d3e5-34d7-41a2-9abd-77cce57c210a.png)
Top line uses 3D-Shadow colors settings, bottom line uses 3D-DarkShadow colors settings.

Menus exist in two ways; with bit 17 of UserPreferenceMask enabled, or disabled. In Windows XP, bit 17 was disabled when classic theme was enabled, is enabled when visual style was enabled, because the visual style engine in Windows XP did not support menus. Starting with Windows Vista, the visual style changed to support menus, but bit 17 still exists (and is enabled by default). It is also this bit that controls the presence of the Menubar and Menuhilight colors parameters (which only exist when bit 17 is activated).

So here is a screenshot of a menu with bit 17 enabled. Menu edges are controlled only by the 3D-Shadow color setting.

![notepad_BoGm7CeodR](https://user-images.githubusercontent.com/100134023/183255310-0170203d-9bfe-4915-b66a-68bbf51345cc.png)

Now here is a screenshot of a menu with bit 17 disabled. Menu edges are controlled in exactly the same way as scrollbar and combobox buttons. That is, like buttons, but with the 3D-Light and 3D-Hilight color settings reversed.

![notepad_D5uxnDRf5q](https://user-images.githubusercontent.com/100134023/183255521-7c2ad4ac-adbd-4c14-a743-aba6392998d7.png)

**Comment by OrthodoxWindows** [comment]
Sorry to escalate the issue, but ClientEdge colors are still not correct in version 1.0.4.1 ; the ClientEdge bottom bar is displayed all the time in black, when it should be displayed with the 3D-DarkShadow color setting.
Also, the menu displays the correct colors, but not in the correct order.

**Comment by Abdelrhman-AK** [comment]
I'm sorry for my late response... I didn't notice this message..
I have fixed other issues in Win32UI. Can you post here some screenshots to make sure if I've fixed it or not?

**Comment by OrthodoxWindows** [comment]
In fact, after posting my message, I realized that I had absolutely not been clear. So I posted the two issues separately, in new topics: https://github.com/Abdelrhman-AK/WinPaletter/issues/27 https://github.com/Abdelrhman-AK/WinPaletter/issues/ 26

So you can ignore my message.

**Comment by Abdelrhman-AK** [comment]
Ok. That is fine.
