### ISSUE TITLE
When trying to set a bigger font size it always set it to tiny after log in:x: [Error] 

### ISSUE THREAD

**Issue by Mac3DX** [Abdelrhman-AK/WinPaletter#205]
## **Describe the error**
When trying to set a bigger font size it always set it to very tiny after log in into Win 11.

## **How to reproduce the error**
- Write here the steps (starting from opening the application) that causes the error.

## **WinPaletter Log**
- If an exception error occurred, press on `copy details` and paste them here. 
- The details will include info about WinPaletter version, date, current OS, exception error message & stack trace.

## **Screenshots/Screen records**
- Don't add screenshot to exception error dialog if you already wrote WinPaletter Log.
- If possible, add screenshots/Screen records of the wrong behaviour to help explain your problem.

## **Additional context**
- Add any other context about the problem here.

**Comment by Abdelrhman-AK** [comment]
This bug is due to wrong behavoiur in Windows when manipulating fonts in registry with high DPI. #76

These steps can solve your problem:
- Set DPI to 100%
- Open WinPaletter and open Metrics and Fonts
- Press on `Defaults Windows` button above
- Make sure that the toggle is enabled
- Press on Load and the apply the theme from the main form
- Return to Windows Metrics and Fonts
- Make the toggle disabed to prevent further actions
- Press on load and re-apply from the main form (To save the disabled toggle into registry)
- Reset your DPI to your previous number

**Comment by Mac3DX** [comment]
Hey, I almost had a heart attack. Thanks for the support.
Is there a way to get the system font a bit bolder now? The Windows font is too thin. Every time after a Win update I get screwed, I just need peace, oh God!

**Comment by Mac3DX** [comment]
I could still notice that there are some menus with tiny fonts. For example, the Edge browser. Take a look at the screenshot.

<img width="551" alt="Screenshot 2023-12-13 175935" src="https://github.com/Abdelrhman-AK/WinPaletter/assets/122476797/762bd42e-28c4-4993-a688-e2eefd1a3913">

**Comment by Abdelrhman-AK** [comment]
> Is there a way to get the system font a bit bolder now? The Windows font is too thin. Every time after a Win update I get screwed, I just need peace, oh God!

You can try reseting metrics and fonts using this registry: repeat the previous steps without opening WinPaletter. (set DPI to 100, merge registry file and reset DPI), and try restarting Windows.

[0.zip](https://github.com/Abdelrhman-AK/WinPaletter/files/13666071/0.zip)

And for Edge browser, try also the previous steps and restart Windows. I don't know why Edge did this strange behaviour.
