### ISSUE TITLE
After restarting, most metrics & fonts settings go back to default.

### ISSUE THREAD

**Issue by tommy141x** [Abdelrhman-AK/WinPaletter#221]
# **❓ Question or spport request**

## **Describe your question or ask for support\help.**

I have my theme saved and applied with a custom font for the Titlebar, Icons, and Menus, along with extra padding for the title bar. When I click apply, everything looks correct. However, after restarting the fonts go back to Segoe UI and the titlebar padding is reset. The second time I tried and restarted the desktop font stayed but the other fonts reset again. I'm on Windows 23H2, any idea how I can troubleshoot this?

**Comment by Abdelrhman-AK** [comment]
I will reproduce this and fix the issue.

**Comment by Abdelrhman-AK** [comment]
- I tried to reproduce it. The preferences didn't change for me:
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/59510211/1937435a-781e-4494-abd1-0f277a7b2681)

- The only expected behavior is that titlebar fonts cannot be changed in Windows 11, only the titlebar font size.

- Do you use WinPaletter for another user account on your Windows? This could be relevant to your issue and is also expected.

**Comment by tommy141x** [comment]
* > The only expected behavior is that titlebar fonts cannot be changed in Windows 11, only the titlebar font size.

I was unaware of this ^, I believe that's what was getting reset.

This can then be closed, thank you!

**Comment by Abdelrhman-AK** [comment]
You are welcome!
