### ISSUE TITLE
Extended Support for Windows 7 and Windows 8.1

### ISSUE THREAD

**Issue by MesterPerfect** [Abdelrhman-AK/WinPaletter#23]
hello
I am a fan of Windows 8.1 and Windows 7 and I use them on some of my devices
Is there a version of your software that works on Windows 7 and Windows 8.1
Thanks

**Comment by Abdelrhman-AK** [comment]
I worked on this days ago, and found CLR20R3 Error on both Windows 8.1 and Windows 7.
It is due to Cyotek Color Picker component inside WinPaletter used to pick colors. I'll try to solve this and if it solved, I'll push and update with extended support to Windows 8.1 and Windows 7.

![Untitled](https://user-images.githubusercontent.com/59510211/184493313-e422708f-3a0a-424b-8a43-355978fb0e0e.png)
![2](https://user-images.githubusercontent.com/59510211/184493304-2041794c-0234-41f8-a249-529f805f4f12.png)

**Comment by MesterPerfect** [comment]
> I worked on this days ago, and found CLR20R3 Error on both Windows 8.1 and Windows 7. It is due to Cyotek Color Picker component inside WinPaletter used to pick colors. I'll try to solve this and if it solved, I'll push an update with extended support to Windows 8.1 and Windows 7.
> 
> ![Untitled](https://user-images.githubusercontent.com/59510211/184493313-e422708f-3a0a-424b-8a43-355978fb0e0e.png) ![2](https://user-images.githubusercontent.com/59510211/184493304-2041794c-0234-41f8-a249-529f805f4f12.png)
 
Can I change colors manually through the registry keys or something like that?

**Comment by Abdelrhman-AK** [comment]
You can change them manually. The goal of the apps to make this easier...

**Comment by MesterPerfect** [comment]
> You can change them manually. The goal of the apps to make this easier...
OK, waiting your program
