### ISSUE TITLE
Bug fix/feature request: To add Title bar text color. Title text sometimes not visible in some apps after setting title bar color.

### ISSUE THREAD

**Issue by jnxr** [Abdelrhman-AK/WinPaletter#57]
For example, when setting the title bar to black, apps like mspaint are unable to display any text on the title bar due to the title text color conflict, ie same title text color as title bar color.
 
![Its supposed to show Untitled - Paint](https://user-images.githubusercontent.com/39534001/205472984-d5e547a2-90b9-405f-9c9a-7dcbdb58a41c.png)

Being able to set the text color to something else would solve this issue.

**Comment by Abdelrhman-AK** [comment]
### It can be modified in Win32UI > Classic Titlebars > Active Titlebar Text
![Screenshot 2022-12-04 162611](https://user-images.githubusercontent.com/59510211/205496381-d6f2a8ba-d323-409c-902d-6eb1e1e5739f.png)

* Anyway, I remember that in older versions of Windows 11 (21H2 or less) can have colored titlebar text, but here I found that in Windows 11 22621.900 (22H2) doesn't apply this color to all titlebars and I don't know the exact reason for this!

**Comment by jnxr** [comment]
Oh, I see. I'm able to change TitleText, but InactiveTitleText isn't working. Is it due to changes in Windows? I'm on the same version. [22621.900]

**Comment by jnxr** [comment]
Oh, I see. I'm able to change TitleText from Win32UI itself, but for whatever reason InactiveTitleText isn't working. Is it due to changes in Windows? I'm on the same version. [22621.900]

Also, InactiveTitleText didn't work for me even through the registry edit. Until now, I used to manually change the values at: Computer\HKEY_CURRENT_USER\Control Panel\Colors & restart the system.
But after another restart, or sometimes even without one, TitleText used to go back to the way it was. InactiveTitleText failed to apply under all conditions.

**Comment by Abdelrhman-AK** [comment]
### I'm sorry, I won't be able to fix that as this issue is mainly due to Microsoft's way in handling registry colors:
- In Windows 11 (Either normal or High Contrast Theme (Aero Lite)): It didn't work for me.
- In Windows 10: Color not applied anywhere, except for Inactive Titlebar Color (applied in explorer window -not all apps-).
- In Windows 8.1: Didn't work except if Aero Lite theme is enabled.
- In Windows 7: Didn't work except if Classic theme is enabled.


Simply, `HKEY_CURRENT_USER\Control Panel\Colors` is the key where the colors are stored for the classic themes (Windows 95 and later).
With introduction of Microsoft Visual Styles (Windows XP and Later), the theme gets some colors (Like Titlebar Text) from the Visual Styles File itself and the rest from the registry (Like Menus, Hilight, ...)


### **And this is the reason of incomplete applying colors, for example, you can find that cursor hilight can be customized while other items not. To fix this issue there are two ways: To Force the classic theme (if you like) or you can find a visual styles online and apply it.**


This is a simple explanation for what I mean:
![vs](https://user-images.githubusercontent.com/59510211/205664740-5dca36e5-80fa-470c-a0d8-7c1ca11944a4.png)
If you open the visual styles by a visual styles editors, you will find many properties can be modified and they are not stored in registry.

**Comment by jnxr** [comment]
Thanks for the quick replies. Also, is there a way to decouple Task Manager's accent color from the Accent color chosen for Start, Taskbar and Action Center? The one which gets applied automatically is not readable at all.

**Comment by Abdelrhman-AK** [comment]
Unfortunately no, there is no way to separate this color. 
Microsoft made the newest task manager has its accent from the first color in registry array `Item 1: Start, Taskbar and Action Center`

**Comment by jnxr** [comment]
Thanks once again. I am checking out the mystyleEditor, and the visual styles available, but from my short searches, I didn't find many. I shall try making one in case I don't find anything suitable. Are the theme files similar to these .mystyles files? Do I need any program to make one or just via the Personalization Settings page?

**Comment by Abdelrhman-AK** [comment]
You're welcome!

> Are the theme files similar to these .mystyles files?

No, they are different. The effective one is .msstyles

> Do I need any program to make one or just via the Personalization Settings page?

Actually you will need 2 programs, or 3

1. [msstyleEditor - Github](https://github.com/nptr/msstyleEditor); copy `C:\Windows\Resources\Themes\aero` to a new folder and work on it.
2. [SecureUxTheme - Github](https://github.com/namazso/SecureUxTheme); and this is to apply the theme you made.
3. `Optional` A Virtual Machine to test the theme and avoid crashes\bugs\undesired action on your main device.

**Comment by Abdelrhman-AK** [comment]
Thank you and good luck!
